[package]
name = "Idris2-Universe-Wiki"
version = "0.3.0"
ipkg = "Idris2-Universe-Wiki.ipkg"

[custom.all.Idris2-Multiset-Core]
type = "local"
path = "../Idris2-Multiset-Core"
ipkg = "Idris2-Multiset-Core.ipkg"

[custom.all.Idris2-Multiset-Transform]
type = "local"
path = "../Idris2-Multiset-Transform"
ipkg = "Idris2-Multiset-Transform.ipkg"

[custom.all.Idris2-Multiset-Binary]
type = "local"
path = "../Idris2-Multiset-Binary"
ipkg = "Idris2-Multiset-Binary.ipkg"

[custom.all.Idris2-Multiset-Ternary]
type = "local"
path = "../Idris2-Multiset-Ternary"
ipkg = "Idris2-Multiset-Ternary.ipkg"

[custom.all.Idris2-Geometry]
type = "local"
path = "../Idris2-Geometry"
ipkg = "Idris2-Geometry.ipkg"

[custom.all.Idris2-Physics]
type = "local"
path = "../Idris2-Physics"
ipkg = "Idris2-Physics.ipkg"

[custom.all.Idris2-Hadron]
type = "local"
path = "../Idris2-Hadron"
ipkg = "Idris2-Hadron.ipkg"

[custom.all.Idris2-Chemistry]
type = "local"
path = "../Idris2-Chemistry"
ipkg = "Idris2-Chemistry.ipkg"

[custom.all.Idris2-Biology]
type = "local"
path = "../Idris2-Biology"
ipkg = "Idris2-Biology.ipkg"

[custom.all.Idris2-Universe]
type = "local"
path = "../Idris2-Universe"
ipkg = "Idris2-Universe.ipkg"
